# Generated by Django 5.0.1 on 2024-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(max_length=255, verbose_name='Направление'),
        ),
    ]
